import type { DemoAccount, TransportProvider } from "./types"

export const DEMO_ACCOUNTS: DemoAccount[] = [
  {
    id: "alex",
    account_id: "cd89d17b-44be-4da6-9f54-d025373e163f",
    name: "Alex Thompson",
    description: "Frequent commuter using multiple transport modes",
    avatar: "/peep-58.svg",
  },
  {
    id: "farah",
    account_id: "66ca7e6b-3972-418e-94c1-08bc93fa1d2",
    name: "Farah Khan",
    description: "Weekend traveler and occasional business trips",
    avatar: "/peep-38.svg",
  },
  {
    id: "gina",
    account_id: "62482e11-3c8e-4ee0-87cf-65cfa26eebf8",
    name: "Gina Rosetti",
    description: "Urban explorer using eco-friendly transport",
    avatar: "/peep-37.svg",
  },
  {
    id: "jordan",
    account_id: "23638779-4dc5-4fa9-a63f-d41d4b15e134",
    name: "Jordan Chen",
    description: "Business traveler with mixed transport preferences",
    avatar: "/peep-7.svg",
  },
]

export const TRANSPORT_PROVIDERS: TransportProvider[] = [
  {
    id: "tfl",
    name: "Transport for London (TfL)",
    logo: "/logos/transport-for-london-logo.svg",
    description: "London public transport network",
    connected: false,
  },
  {
    id: "avanti_west_coast",
    name: "Avanti West Coast",
    logo: "/logos/avanti-west-coast-logo.svg",
    description: "High-speed rail services",
    connected: false,
  },
  {
    id: "stagecoach",
    name: "Stagecoach Group",
    logo: "/logos/stagecoach-group-logo.svg",
    description: "UK-wide bus and coach operator",
    connected: false,
  },
  {
    id: "trainline",
    name: "Trainline",
    logo: "/logos/trainline-logo.svg",
    description: "UK and European train booking",
    connected: false,
  },
  {
    id: "lner",
    name: "London North Eastern Railway (LNER)",
    logo: "/logos/lner-logo.svg",
    description: "Intercity rail services",
    connected: false,
  },
  {
    id: "gwr",
    name: "Great Western Railway (GWR)",
    logo: "/logos/gwr-logo.svg",
    description: "South West and Wales rail",
    connected: false,
  },
  {
    id: "thameslink",
    name: "Thameslink",
    logo: "/logos/thameslink-logo.svg",
    description: "London and South East rail",
    connected: false,
  },
  {
    id: "scotrail",
    name: "ScotRail",
    logo: "/logos/scotrail-logo.svg",
    description: "Scotland rail network",
    connected: false,
  },
  {
    id: "crosscountry",
    name: "CrossCountry",
    logo: "/logos/crosscountrytrains-logo.svg",
    description: "UK-wide intercity rail",
    connected: false,
  },
  {
    id: "northern",
    name: "Northern",
    logo: "/logos/northerntrains-logo.svg",
    description: "North of England rail",
    connected: false,
  },
  {
    id: "transpennine_express",
    name: "TransPennine Express",
    logo: "/logos/transpennine-logo.svg",
    description: "North and Scotland rail",
    connected: false,
  },
  {
    id: "southeastern",
    name: "Southeastern",
    logo: "/logos/southeastern-logo.svg",
    description: "South East England rail",
    connected: false,
  },
  {
    id: "southern",
    name: "Southern",
    logo: "/logos/southern-logo.svg",
    description: "South London and coast rail",
    connected: false,
  },
  {
    id: "south_western_railway",
    name: "South Western Railway",
    logo: "/logos/south-western-railway-logo.svg",
    description: "South West England rail",
    connected: false,
  },
  {
    id: "chiltern_railways",
    name: "Chiltern Railways",
    logo: "/logos/chiltern_railw_logo.svg",
    description: "London to Midlands rail",
    connected: false,
  },
  {
    id: "firstgroup",
    name: "FirstGroup",
    logo: "/logos/firstgroup-logo.svg",
    description: "UK-wide bus operator",
    connected: false,
  },
  {
    id: "go_ahead",
    name: "Go-Ahead Group",
    logo: "/logos/go-ahead-logo.svg",
    description: "UK-wide bus operator",
    connected: false,
  },
  {
    id: "arriva",
    name: "Arriva",
    logo: "/logos/arriva-logo.svg",
    description: "UK-wide bus operator",
    connected: false,
  },
  {
    id: "metroline",
    name: "Metroline",
    logo: "/logos/metrolinel-logo.svg",
    description: "London bus operator",
    connected: false,
  },
  {
    id: "lothian_buses",
    name: "Lothian Buses",
    logo: "/logos/lothianbuses-logo.svg",
    description: "Edinburgh bus operator",
    connected: false,
  },
  {
    id: "reading_buses",
    name: "Reading Buses",
    logo: "/logos/reading-buses-logo.svg",
    description: "Reading city bus operator",
    connected: false,
  },
  {
    id: "blackpool_transport",
    name: "Blackpool Transport",
    logo: "/logos/blackpool-transport-seeklogo.svg",
    description: "Blackpool bus and tram operator",
    connected: false,
  },
  {
    id: "transport_for_greater_manchester",
    name: "Transport for Greater Manchester",
    logo: "/logos/TfGM-logo.svg",
    description: "Manchester public transport network",
    connected: false,
  },
]
