import type { DemoAccount, TransportProvider } from "./types"

export const DEMO_ACCOUNTS: DemoAccount[] = [
  {
    id: "alex",
    account_id: "cd89d17b-44be-4da6-9f54-d025373e163f",
    name: "Alex Thompson",
    description: "Frequent commuter using multiple transport modes",
    avatar: "/placeholder.svg?height=64&width=64&text=AT",
  },
  {
    id: "sam",
    account_id: "66ca7e6b-3972-418e-94c1-08bc93fa1d2",
    name: "Sam Chen",
    description: "Weekend traveler and occasional business trips",
    avatar: "/placeholder.svg?height=64&width=64&text=SC",
  },
  {
    id: "jordan",
    account_id: "62482e11-3c8e-4ee0-87cf-65cfa26eebf8",
    name: "Jordan Williams",
    description: "Urban explorer using eco-friendly transport",
    avatar: "/placeholder.svg?height=64&width=64&text=JW",
  },
  {
    id: "taylor",
    account_id: "23638779-4dc5-4fa9-a63f-d41d4b15e134",
    name: "Taylor Davis",
    description: "Business traveler with mixed transport preferences",
    avatar: "/placeholder.svg?height=64&width=64&text=TD",
  },
]

export const TRANSPORT_PROVIDERS: TransportProvider[] = [
  {
    id: "tfl",
    name: "Transport for London (TfL)",
    logo: "/logos/transport-for-london-logo.svg",
    description: "London public transport network",
    connected: false,
  },
  {
    id: "avanti_west_coast",
    name: "Avanti West Coast",
    logo: "/logos/avanti-west-coast-logo.svg",
    description: "High-speed rail services",
    connected: false,
  },
  {
    id: "stagecoach",
    name: "Stagecoach Group",
    logo: "/logos/stagecoach-group-logo.svg",
    description: "UK-wide bus and coach operator",
    connected: false,
  },
  {
    id: "trainline",
    name: "Trainline",
    logo: "/logos/trainline-logo.svg",
    description: "UK and European train booking",
    connected: false,
  },
  {
    id: "lner",
    name: "London North Eastern Railway (LNER)",
    logo: "/placeholder.svg?height=40&width=120&text=LNER",
    description: "Intercity rail services",
    connected: false,
  },
  {
    id: "gwr",
    name: "Great Western Railway (GWR)",
    logo: "/placeholder.svg?height=40&width=120&text=GWR",
    description: "South West and Wales rail",
    connected: false,
  },
  {
    id: "thameslink",
    name: "Thameslink",
    logo: "/placeholder.svg?height=40&width=120&text=Thameslink",
    description: "London and South East rail",
    connected: false,
  },
  {
    id: "scotrail",
    name: "ScotRail",
    logo: "/placeholder.svg?height=40&width=120&text=ScotRail",
    description: "Scotland rail network",
    connected: false,
  },
  {
    id: "crosscountry",
    name: "CrossCountry",
    logo: "/placeholder.svg?height=40&width=120&text=CrossCountry",
    description: "UK-wide intercity rail",
    connected: false,
  },
  {
    id: "northern",
    name: "Northern",
    logo: "/placeholder.svg?height=40&width=120&text=Northern",
    description: "North of England rail",
    connected: false,
  },
  {
    id: "transpennine_express",
    name: "TransPennine Express",
    logo: "/placeholder.svg?height=40&width=120&text=TPE",
    description: "North and Scotland rail",
    connected: false,
  },
  {
    id: "southeastern",
    name: "Southeastern",
    logo: "/placeholder.svg?height=40&width=120&text=Southeastern",
    description: "South East England rail",
    connected: false,
  },
  {
    id: "southern",
    name: "Southern",
    logo: "/placeholder.svg?height=40&width=120&text=Southern",
    description: "South London and coast rail",
    connected: false,
  },
  {
    id: "south_western_railway",
    name: "South Western Railway",
    logo: "/placeholder.svg?height=40&width=120&text=SWR",
    description: "South West England rail",
    connected: false,
  },
  {
    id: "chiltern_railways",
    name: "Chiltern Railways",
    logo: "/placeholder.svg?height=40&width=120&text=Chiltern",
    description: "London to Midlands rail",
    connected: false,
  },
  {
    id: "firstgroup",
    name: "FirstGroup",
    logo: "/placeholder.svg?height=40&width=120&text=FirstGroup",
    description: "UK-wide bus operator",
    connected: false,
  },
  {
    id: "go_ahead",
    name: "Go-Ahead Group",
    logo: "/placeholder.svg?height=40&width=120&text=Go-Ahead",
    description: "UK-wide bus operator",
    connected: false,
  },
  {
    id: "arriva",
    name: "Arriva",
    logo: "/placeholder.svg?height=40&width=120&text=Arriva",
    description: "UK-wide bus operator",
    connected: false,
  },
  {
    id: "metroline",
    name: "Metroline",
    logo: "/placeholder.svg?height=40&width=120&text=Metroline",
    description: "London bus operator",
    connected: false,
  },
  {
    id: "lothian_buses",
    name: "Lothian Buses",
    logo: "/placeholder.svg?height=40&width=120&text=Lothian",
    description: "Edinburgh bus operator",
    connected: false,
  },
  {
    id: "reading_buses",
    name: "Reading Buses",
    logo: "/placeholder.svg?height=40&width=120&text=Reading",
    description: "Reading city bus operator",
    connected: false,
  },
  {
    id: "blackpool_transport",
    name: "Blackpool Transport",
    logo: "/placeholder.svg?height=40&width=120&text=Blackpool",
    description: "Blackpool bus and tram operator",
    connected: false,
  },
  {
    id: "transport_for_greater_manchester",
    name: "Transport for Greater Manchester",
    logo: "/placeholder.svg?height=40&width=120&text=TfGM",
    description: "Manchester public transport network",
    connected: false,
  },
]
